sudo: required
dist: trusty
language: python
python:
  - 2.7.11
virtualenv:
  system_site_package: true

install:
  - echo $TRAVIS_PYTHON_VERSION
  - pip install -U -r ./requirements.txt
  - pip install tensorflow
  - wget https://www.dropbox.com/s/cd0drt6t9q1mwg0/deeplab_resnet.ckpt?dl=1 -O deeplab_resnet.ckpt
  
script:
  - python inference.py ./misc/2007_000129.jpg ./deeplab_resnet.ckpt
  - python train.py --batch-size 1 --data-dir ./ --data-list ./dataset/debug.txt --num-steps 10 --restore-from ./deeplab_resnet.ckpt --save-num-images 1
  - python train_msc.py --batch-size 1 --data-dir ./ --data-list ./dataset/debug.txt --num-steps 10 --restore-from ./deeplab_resnet.ckpt --save-num-images 1
  - python evaluate.py --data-dir ./ --data-list ./dataset/debug.txt --num-steps 1 --restore-from ./deeplab_resnet.ckpt
